/*
 * This source file was generated by the Gradle 'init' task
 */
package org.ticketBooking;

import org.ticketBooking.services.UserBookingService;

import java.io.IOException;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        System.out.println("Running Train Booking System");
        Scanner scanner = new Scanner(System.in);
        int option = 0;
        UserBookingService userBookingService;
        try{
            userBookingService = new UserBookingService();
        }catch (IOException ex){
            System.out.println("There is something wrong");
            return;
        }
        while(option!=7){

        }
    }
}
